<?php

namespace ContainerDM1fpSr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__IWl39Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..i_wl39' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..i_wl39'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.8IE8w_v', 'get_ServiceLocator_8IE8wVService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.8IE8w_v', 'get_ServiceLocator_8IE8wVService', true],
            'App\\Controller\\PostController::delete' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Controller\\PostController::edit' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.8IE8w_v', 'get_ServiceLocator_8IE8wVService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.8IE8w_v', 'get_ServiceLocator_8IE8wVService', true],
            'App\\Controller\\PostController:delete' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Controller\\PostController:edit' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\PostController::delete' => '?',
            'App\\Controller\\PostController::edit' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\PostController:delete' => '?',
            'App\\Controller\\PostController:edit' => '?',
            'App\\Controller\\PostController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
