<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDM1fpSr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDM1fpSr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDM1fpSr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDM1fpSr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDM1fpSr\App_KernelDevDebugContainer([
    'container.build_hash' => 'DM1fpSr',
    'container.build_id' => '18c5aa5c',
    'container.build_time' => 1687773876,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDM1fpSr');
